#!/usr/bin/env bash
# build-index.sh
#
# Generates INDEX-BY-DATE.md and INDEX-BY-TARGET.md from the prs/
# directory. Runs locally (or from a future GitHub Action) on push.
#
# Each PR file is parsed for its Target, PR URL, Opened date, and
# Status. Entries that don't parse are listed at the bottom of each
# index under "Unparsed".

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PRS_DIR="$REPO_DIR/prs"
BY_DATE="$REPO_DIR/INDEX-BY-DATE.md"
BY_TARGET="$REPO_DIR/INDEX-BY-TARGET.md"

if [ ! -d "$PRS_DIR" ]; then
  mkdir -p "$PRS_DIR"
fi

# Collect: tab-separated rows of date<TAB>target<TAB>pr_url<TAB>status<TAB>file
ROWS=$(mktemp)
UNPARSED=$(mktemp)
trap 'rm -f "$ROWS" "$UNPARSED"' EXIT

shopt -s nullglob
for f in "$PRS_DIR"/*.md; do
  rel="prs/$(basename "$f")"
  target=$(grep -m1 -E '^\| Target \| ' "$f" 2>/dev/null \
    | sed -E 's/^\| Target \| //; s/ \|$//; s/.*\[(.*)\]\(.*\).*/\1/' || true)
  pr_url=$(grep -m1 -E '^\| PR \| ' "$f" 2>/dev/null \
    | sed -E 's/^\| PR \| //; s/ \|$//; s/.*\((https?:\/\/[^)]+)\).*/\1/' || true)
  opened=$(grep -m1 -E '^\| Opened \| ' "$f" 2>/dev/null \
    | sed -E 's/^\| Opened \| //; s/ \|$//' || true)
  status=$(grep -m1 -E '^\| Status \| ' "$f" 2>/dev/null \
    | sed -E 's/^\| Status \| //; s/ \|$//' || true)

  if [ -z "$target" ] || [ -z "$pr_url" ] || [ -z "$opened" ]; then
    echo "$rel" >> "$UNPARSED"
    continue
  fi

  printf '%s\t%s\t%s\t%s\t%s\n' "$opened" "$target" "$pr_url" "${status:-?}" "$rel" >> "$ROWS"
done

# Build INDEX-BY-DATE.md
{
  echo "# Index by date"
  echo
  echo "Newest first. Auto-generated by \`scripts/build-index.sh\`."
  echo
  echo "| Date | Target | PR | Status | Entry |"
  echo "|---|---|---|---|---|"
  if [ -s "$ROWS" ]; then
    sort -r "$ROWS" | while IFS=$'\t' read -r date target pr_url status rel; do
      pr_short=$(echo "$pr_url" | sed -E 's|.*/pull/([0-9]+).*|#\1|')
      echo "| ${date} | [${target}](https://github.com/${target}) | [${pr_short}](${pr_url}) | ${status} | [open](${rel}) |"
    done
  else
    echo "| — | — | — | — | — |"
  fi
  if [ -s "$UNPARSED" ]; then
    echo
    echo "## Unparsed"
    echo
    while IFS= read -r rel; do
      echo "- [${rel}](${rel})"
    done < "$UNPARSED"
  fi
} > "$BY_DATE"

# Build INDEX-BY-TARGET.md
{
  echo "# Index by target"
  echo
  echo "Grouped by \`owner/repo\`. Auto-generated by \`scripts/build-index.sh\`."
  echo
  if [ -s "$ROWS" ]; then
    cut -f2 "$ROWS" | sort -u | while IFS= read -r target; do
      echo "## [${target}](https://github.com/${target})"
      echo
      echo "| Date | PR | Status | Entry |"
      echo "|---|---|---|---|"
      grep -P "\t${target}\t" "$ROWS" | sort -r | while IFS=$'\t' read -r date t pr_url status rel; do
        pr_short=$(echo "$pr_url" | sed -E 's|.*/pull/([0-9]+).*|#\1|')
        echo "| ${date} | [${pr_short}](${pr_url}) | ${status} | [open](${rel}) |"
      done
      echo
    done
  else
    echo "_No entries yet._"
  fi
  if [ -s "$UNPARSED" ]; then
    echo
    echo "## Unparsed"
    echo
    while IFS= read -r rel; do
      echo "- [${rel}](${rel})"
    done < "$UNPARSED"
  fi
} > "$BY_TARGET"

echo "Wrote $(basename "$BY_DATE") and $(basename "$BY_TARGET")."
echo "Entries: $(wc -l < "$ROWS" | tr -d ' '). Unparsed: $(wc -l < "$UNPARSED" | tr -d ' ')."
